name: Tox tests

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libkrb5-dev
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libkrb5-dev
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          verbose: true
  bandit-exitzero:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3-bandit-exitzero
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py3-bandit
